package Token;

public enum TokenType {
    BLOCK_COMMENT,
    LINE_COMMENT,
    TAB,
    WHITE_SPACE,
    END_LINE,
    OPEN_BRACKET,
    CLOSE_BRACKET,
    OPEN_CURLY_BRACKET,
    CLOSE_CURLY_BRACKET,
    COMMA,
    VOID,
    FALSE,
    TRUE,
    NULL,
    RETURN,
    NEW,
    CLASS,
    IF,
    ELSE,
    WHILE,
    FOR,
    CLONE,
    SEMICOLON,
    COLON,
    PLUS,
    MINUS,
    MULTIPLY,
    DIVIDE,
    POINT,
    EQUAL,
    EQUALX_2,
    DIFFER,
    GREATER,
    LESS,
    SCREAMER,
    STATIC,
    PUBLIC,
    PRIVATE,
    INT,
    DOUBLE,
    STRING,
    STRING_CONSTANT,
    DOUBLE_CONSTANT,
    INT_CONSTANT,
    SEARCH_ENGINE,
    SEARCH_RESULT,
    SEARCH_RESULTS,
    QUERY,
    FILE,
    KEYWORD,
    IDENTIFIER;

    public boolean isCommentOrWhiteSign(){
        return this == BLOCK_COMMENT || this == LINE_COMMENT || this == WHITE_SPACE || this == TAB || this == END_LINE;
    }
}
